# Services definition for building & deploying

name: epita-it

services:

  app:
    # Extend
    extends:
      file: ./app/docker-compose.yml
      service: app
    # Build override
    image: ${IMAGES_PREFIX:-app}:${IMAGES_TAG:-latest}
    # Deploy override
    ports: !override
      - ${APP_PORT:-8080}:${APP_DOCKER_PORT:-8080}  # HTTP
